ft/test-config
browng-io/rony-o-cloud pull request #21
Opened 2022-08-13 05:42 UTC by bibi-ic

2022-08-13 06:28 UTC, 9bany requested changes
Please, improve your testcases

2022-08-13 06:28 UTC, 9bany commented on config/config_test.go
> +	t.Run("Config file set", func(t *testing.T) {
Clear this file with testcases list

2022-08-13 12:14 UTC, bibi-ic commented on config/config_test.go
> +	t.Run("Config file set", func(t *testing.T) {
resolved @9bany

2022-08-15 01:19 UTC, 9bany requested changes

2022-08-15 01:19 UTC, 9bany commented on config/config_test.go
> +			file, err := fs.Create(absFilePath)
please ! remove your env file after test running !

2022-08-15 01:25 UTC, bibi-ic commented on config/config_test.go
> +			file, err := fs.Create(absFilePath)
@9bany this is virtual env from afero package Sifu.

So is does not create any on local test

https://github.com/spf13/afero#using-afero-for-testing

2022-08-15 01:29 UTC, 9bany requested changes

2022-08-15 01:29 UTC, 9bany commented on config/config_test.go
> +			var config Config
move from line 93-101 to a function

2022-08-15 02:11 UTC, bibi-ic commented on config/config_test.go
> +			var config Config
@9bany resolved

2022-08-15 13:16 UTC, merged